# Generated by Django 3.2.9 on 2021-12-18 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlist', '0005_track_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='link',
        ),
    ]
